### ISSUE TITLE
MacOS not installing properly

### ISSUE THREAD

**Issue by Playerrrrr** [reorproject/reor#25]
Have MacOS 14, could be an update issue. But the .dmg install file is asking me to download the latest version of the software and not allowing me to even open Reor.

**Comment by samlhuillier** [comment]
As far as I'm aware MacOS 14 is latest...Could you send me the exact message it is saying when you try to open the dmg? This could be a security issue in which case you need to go to settings -> security, scroll to where it  hit "Open anyway":
<img width="475" alt="Screenshot 2024-02-08 at 21 03 02" src="https://github.com/reorproject/reor/assets/17236551/677b475d-edf0-4cd9-92d2-424006453baf">

**Comment by tudorsaitoc** [comment]
this worked for me

**Comment by jacob-lee** [comment]
This did not work for me. The app immediately crashes with the following message:

```
Uncaught Exception:
Error: vectordb: failed to load native library.
You may need to run `npm install @lancedb/vectordb-darwin-arm64`.

If that does not work, please file a bug report at https://github.com/lancedb/lancedb/issues

Source error: Error: dlopen(/Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node, 0x0001): Library not loaded: /opt/homebrew/opt/xz/lib/liblzma.5.dylib
Referenced from: <84349C78-366A-35F8-8798-808072CCD3D8> /Applications/Reor.app/Contents/Resources/app.asar.unpacked/node_modules/@lancedb/vectordb-darwin-arm64/index.node (built for macOS 14.0 which is newer than running OS)
Reason: tried: '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file), '/opt/homebrew/opt/xz/lib/liblzma.5.dylib' (no such file)
at Object.<anonymous> (/Applications/Reor.app/Contents/Resources/app.asar/node_modules/vectordb/native.js:26:11)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
at Module.load (node:internal/modules/cjs/loader:1126:32)
at Module._load (node:internal/modules/cjs/loader:967:12)
at c._load (node:electron/js2c/node_init:2:13672)
at Module.require (node:internal/modules/cjs/loader:1150:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/Applications/Reor.app/Contents/Resources/app.asar/node_modules/vectordb/dist/query.js:19:25)
at Module._compile (node:internal/modules/cjs/loader:1271:14)
```

I'm running Apple M1 Max, Ventura 13.6.3 and installed Reor_0.1.43-arm64.dmg

**Comment by gitjeff05** [comment]
I cannot open the binary for Mac (Intel):

![Screenshot 2024-02-15 at 10 18 14 AM](https://github.com/reorproject/reor/assets/548922/c0d4c54b-ccd1-4632-8342-2eeab710749f)

I am on MacOS 14.3.1
2.6 GHz 6-Core Intel Core i7

**Comment by swyxio** [comment]
hold down option key when you open the app. its apple imposing a bullshit $99 devleoper tax to make us jump thru code signing hoops

**Comment by jacob-lee** [comment]
Not sure what that is supposed to do, but I still get the pop up with the
JavaScript uncaught exception.

**Comment by samlhuillier** [comment]
@jacob-lee this is related to #36 which should be fixed on MacOS from [v0.1.44](https://github.com/reorproject/reor/releases/tag/v0.1.44). 

Are you on Windows? This bug still exists on windows and a workaround is to install visual studio and then install visual studio c++ libraries.

**Comment by jacob-lee** [comment]
I'm running Apple M1 Max, Ventura 13.6.3 and installed
Reor_0.1.43-arm64.dmg.

The error message I, personally am getting is pasted in my reply above. It
seems to have something to do with you DMG package expecting I have
homebrew installed, or some dependency related to vector databases.. a
problem somewhat unexpected when installing a DMG file.

**Comment by jacob-lee** [comment]
I see. Disregard my previous message; I should have read #36
<https://github.com/reorproject/reor/issues/36> first. I'll give the new
release a try. Thank you!

**Comment by chenrui333** [comment]
fyi, seeing the same sign issue while doing the cask package.

**Comment by jacob-lee** [comment]
This release fixed the issue for me.

**Comment by samlhuillier** [comment]
Which issue were you seeing @chenrui333 ?
