### ISSUE TITLE
Embedding Error Snowflake Ollama

### ISSUE THREAD

**Issue by Fau57** [reorproject/reor#264]
After picking the snowflake embedding model in the options and reloading the vault i get this response: Error: Embedding function error: Error: Resource initialization failed: Error: Pipeline initialization failed for repo Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "C:\Users\user\.ollama\models\manifests\registry.ollama.ai\library/snowflake-arctic-embed/tokenizer.json". Stack Trace: Error: `local_files_only=true` or `env.allowRemoteModels=false` and file was not found locally at "C:\Users\user\.ollama\models\manifests\registry.ollama.ai\library/snowflake-arctic-embed/tokenizer.json". at getModelFile (file:///C:/Users/user/AppData/Local/Programs/Reor/resources/app.asar/node_modules/@xenova/transformers/src/utils/hub.js:462:27) at async getModelJSON (file:///C:/Users/user/AppData/Local/Programs/Reor/resources/app.asar/node_modules/@xenova/transformers/src/utils/hub.js:575:18) at async Promise.all (index 0) at async loadTokenizer (file:///C:/Users/user/AppData/Local/Programs/Reor/resources/app.asar/node_modules/@xenova/transformers/src/tokenizers.js:61:18) at async AutoTokenizer.from_pretrained (file:///C:/Users/user/AppData/Local/Programs/Reor/resources/app
**To Reproduce**
1. Changed model in local embedding model to [snowflake-arctic-embed](https://ollama.com/library/snowflake-arctic-embed) i think its the 33 million model, 
2. Click on close program to reinitialize the vault
3. Reopen Reor
4. See above for error information

**Expected behavior**
my understanding is it should re do the embedding with the new model or am i wrong?

**Desktop (please complete the following information):**
 - OS: win 11
- Hardware: Ryzen 5 5560U and 32 GB ddr4 RAM
 - Version: i think its the most reccent

**Comment by uuur86** [comment]
I guess, Reor only supports "*.onnx" type models.

**Comment by Fau57** [comment]
Oh i must have missed that in my reading sorry my bad

**Comment by uuur86** [comment]
No problem! Just wanted to make sure everything is clear. If you need any further details or assistance, feel free to ask :)

**Comment by Fau57** [comment]
I'm not sure this is your project or you're just a member but I'm wondering
I guess I could just find your roadmap but I was wondering what that looks
like

**Comment by uuur86** [comment]
Sorry, I didn't understand what you mean. But;

I'm a volunteer contributor to this project. 
Open source culture emphasizes collective improvement and shared ownership.
"open source culture" <-- You can search this on google for detailed information..

**Comment by Fau57** [comment]
i am an aspiring developer. I think i am at beginner level for python at least, ANYWAY. I also use the crap outta Obsidian. Im just wondering if there are plans from you guys involved to add more features? or if i should fork and just go to town?

**Comment by uuur86** [comment]
You can follow the Reor project on Discord. There, you can also suggest features and discuss them. https://discord.gg/b7zanGCTUY

**Comment by uuur86** [comment]
Additionally, I believe everyone would be happy to welcome aspiring developers like you to join us!

**Comment by veancn** [comment]
Reor只支持“*.onnx”类型的模型。
> 
> 文件结构必须包含“tokenizer.json、config.json、tokenizer_config.json”文件。缺少的文件可以从 hf 下载（https://huggingface.co/Snowflake/snowflake-arctic-embed-m/tree/main）
> 
> “C:\Users\user.ollama\models\manifests\registry.ollama.ai\library/snowflake-arctic-embed”的目录结构应如下：
> 
> * onnx (目录) 
>   —— model.onnx 
>   —— model_quantized.onnx
> * tokenizer.json
> * ...json
> * tokenizer_config.json

能将目录结构中，不是模型文件的其他4个文件发给我（anlaw@sohu.com）试用吗。我所在的国家登陆不了huggingface.co网站。非常感谢！
