### ISSUE TITLE
Remote LLM only supporting one chat.

### ISSUE THREAD

**Issue by Jflick58** [reorproject/reor#436]
**Describe the bug**
I have a remote LLM that is our internal proxy for Azure OpenAI and Google Gemini. I have configured it properly as it does occasionally work. However, I often get an error pop up:

Error: LLM not found. Stack Trace: Error: LLM not found. at QA (file:///Applications/Reor.app/Contents/Resources/app.asar/dist/assets/index-92e5223c.js:148:644) at async O (file:///Applications/Reor.app/Contents/Resources/app.asar/dist/assets/index-92e5223c.js:259:6679)

**To Reproduce**
1.  Setup Remote LLM (proxied Azure OpenAI GPT-4o)
2. Set default llm to GPT-4o
3. Start a chat. (it will work)
4. Start a new chat with that same LLM (or switch between chats)
5. See error.

**Expected behavior**
Chats should function independently so that I can switch LLMs or have multiple separate chats with the same LLM. 

Barring that, exposing logs or a more informative error message would be helpful. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
- Hardware: MacBook Pro 14-inch, 2021 (M1 Pro 10 core), 16 GB ram
 - Version: Sonoma 14.6.1 

**Additional context**
Love the tool and hope to contribute when I get some free time!

**Comment by Jflick58** [comment]
I did some additional investigation: Running multiple chats is not a problem in v.0.2.19.

**Comment by samlhuillier** [comment]
Hey thanks for reporting this @Jflick58 

I've tried to reproduce it haven't been able to do so so I have two suggestions to try see if we can fix this:
1. Download [v0.2.24](https://github.com/reorproject/reor/releases/tag/v0.2.24) and see if that fixes things
2. If not, I'd suggest we try clearing your local store state (beware that this will delete all chats you have made in Reor). You can do this:

#### Clone repo:
```
git clone https://github.com/reorproject/reor.git
```
#### Install dependencies:
Make sure you have [nodejs](https://nodejs.org/en/download) installed.

```
npm install
```

Inside of ```electron/main/index.ts``` uncomment line 23 so that line 23 should look like this:
```
store.clear() // clear store for testing CAUTION: THIS WILL DELETE YOUR CHAT HISTORY
```

#### Run for dev:
```
npm run dev
```

After doing the above, Reor will open in dev as if it were a fresh install. You can then close the dev version and reopen
