### ISSUE TITLE
indexing error

### ISSUE THREAD

**Issue by gerrampard** [reorproject/reor#52]
indexing error: type error: fetch failed after initialing vector database,  (tried several models, MacOS 14.3.1,  Reor 0.1.45)
![CleanShot 2024-02-17 at 13 58 55@2x](https://github.com/reorproject/reor/assets/63440768/b1fec5fb-2f62-4192-a9da-0651d2cd0e44)

**Comment by kankanai** [comment]
me too

**Comment by imb4dm4n** [comment]
+1

**Comment by samlhuillier** [comment]
I've made several changes to to indexing in the new version: https://github.com/reorproject/reor/releases/tag/v0.1.46
Could you guys try it and let me know if you still get this error

**Comment by gerrampard** [comment]
> I've made several changes to to indexing in the new version: https://github.com/reorproject/reor/releases/tag/v0.1.46 Could you guys try it and let me know if you still get this error

unfortunately, still same error, and now app crash! (submitted the crash report to apple, maybe you can take a look)

**Comment by samlhuillier** [comment]
Would you be able to run from source and send me what shows up in logs, just I don't have much to debug with right now. If you install the latest version of node and run:
```
git clone https://github.com/reorproject/reor
npm install
npm run dev
```
that would be much appreciated :)

**Comment by SYLJX** [comment]
<img width="558" alt="image" src="https://github.com/reorproject/reor/assets/90434432/d063dd37-105a-4480-bc3e-3ec2ba4d7a2a">

**Comment by samlhuillier** [comment]
@SYLJX you need to install node js: https://nodejs.org/en/download

**Comment by kankanai** [comment]
> Would you be able to run from source and send me what shows up in logs, just I don't have much to debug with right now. If you install the latest version of node and run:
> 
> ```
> git clone https://github.com/reorproject/reor
> npm install
> npm run dev
> ```
> 
> that would be much appreciated :)

i do it,but it tips "Indexing error: TypeError: fetch failed. Please try restarting or open a Github issue.

",and the cmd show 

`Failed to initialize pipeline TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:12293:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getModelFile (file:///*****/@xenova+transformers@2.15.0/node_modules/@xenova/transformers/src/utils/hub.js:471:24)
    at async getModelJSON (file:///*****/@xenova+transformers@2.15.0/node_modules/@xenova/transformers/src/utils/hub.js:575:18)
    at async Promise.all (index 0)
    at async loadTokenizer (file:///*****/@xenova+transformers@2.15.0/node_modules/@xenova/transformers/src/tokenizers.js:61:18)
    at async AutoTokenizer.from_pretrained (file:///*****/@xenova+transformers@2.15.0/node_modules/@xenova/transformers/src/tokenizers.js:4343:50)
    at async Promise.all (index 0)
    at async loadItems (file:///*****/@xenova+transformers@2.15.0/node_modules/@xenova/transformers/src/pipelines.js:3116:5)
    at async pipeline (file:///*****/@xenova+transformers@2.15.0/node_modules/@xenova/transformers/src/pipelines.js:3056:21) {
  cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
Error during file indexing: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:12293:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by gerrampard** [comment]
> Would you be able to run from source and send me what shows up in logs, just I don't have much to debug with right now. If you install the latest version of node and run:
> 
> ```
> git clone https://github.com/reorproject/reor
> npm install
> npm run dev
> ```
> 
> that would be much appreciated :)

thanks, indexing ok now, but new error: error saving current file! (when i switch from my markdown files on the menu left??

**Comment by GuoJiaxing1997** [comment]
same error for me

**Comment by SYLJX** [comment]
> @SYLJX you need to install node js: https://nodejs.org/en/download

still the same feedback

**Comment by samlhuillier** [comment]
I suspect this is related to network settings, proxy/vpn/firewall. Could you guys let me know whether you have any of these  and which country you are in etc. I managed to reproduce this by opening a vpn in a different country.

I am working on a patch to make it easier to manually download and add the embedding model if this happens, but would like some more information to solve the root problem.

**Comment by samlhuillier** [comment]
A [new version](https://github.com/reorproject/reor/releases/tag/v0.1.49) is out that allows you to download an embedding model from huggingface and attach it yourself to get around this proxy issue with downloading embedding models from huggingface! 

And a guide to doing this is available [here](https://www.reorproject.org/docs/documentation/embedding).

I am also working on a fix to get around the proxy issues as we speak :)

**Comment by gerrampard** [comment]
> A [new version](https://github.com/reorproject/reor/releases/tag/v0.1.49) is out that allows you to download an embedding model from huggingface and attach it yourself to get around this proxy issue with downloading embedding models from huggingface!
> 
> And a guide to doing this is available [here](https://www.reorproject.org/docs/documentation/embedding).
> 
> I am also working on a fix to get around the proxy issues as we speak :)

Initials indexing and model loading seems ok for me, but APP crash every time when I ASK, i've submmited the crash report to Apple, could you please take a look, thanks

**Comment by samlhuillier** [comment]
Thank you @gerrampard for mentioning.

- Which local model, which context length and how much RAM do you have?

Unfortunately, local models are still fairly new so getting the conditions completely right for avoiding crashes is quite hard :(

Also, did attaching a local embedding model and that fixed the fetch error?

**Comment by gerrampard** [comment]
> Thank you @gerrampard for mentioning.
> 
> * Which local model, which context length and how much RAM do you have?
> 
> Unfortunately, local models are still fairly new so getting the conditions completely right for avoiding crashes is quite hard :(
> 
> Also, did attaching a local embedding model and that fixed the fetch error?

It appears that the crash issue was caused by the model I initially selected (chinese-alpaca-2-7b.Q4_K_M.gguf). The issue is now resolved after switching to a new model (openhermes-2.5-mistral-7b.Q6_K.gguf).

Thank you for this amazing tool and your excellent work. I am looking forward to more features in the future!

p.s.
The fetch error? yes, no errors for now.

**Comment by samlhuillier** [comment]
Great @gerrampard !

I have now pushed out a fix for the proxy issues which should fix this error message entirely, download the model automatically and get rid of this error: https://github.com/reorproject/reor/releases/tag/v0.1.50
@SYLJX @imb4dm4n @kankanai
