### ISSUE TITLE
Error feeding the database

### ISSUE THREAD

**Issue by arnwas** [reorproject/reor#54]
Hi, my first attempt to use this gave this error:

(base) arno@HP21:~/src/AppI$ ./Reor_0.1.45.AppImage
Adding data to DB:
first item:  {
  notepath: '/home/arno/Reor/Website Arno.md',
  content: 'Updates der Termine\n\nDreigroschenoper\n\n',
  subnoteindex: 0,
  timeadded: 2024-02-17T09:35:24.028Z,
  filemodified: 2024-02-17T09:33:19.592Z
}
Chunks:
first chunk:  [
  {
    notepath: '/home/arno/Reor/Website Arno.md',
    content: 'Updates der Termine\n\nDreigroschenoper\n\n',
    subnoteindex: 0,
    timeadded: 2024-02-17T09:35:24.028Z,
    filemodified: 2024-02-17T09:33:19.592Z
  }
]
Adding chunk to DB:
Error adding chunk to DB: TypeError: Table and inner RecordBatch schemas must be equivalent.
    at new Table (/tmp/.mount_Reor_0UZnYj8/resources/app.asar/node_modules/apache-arrow/table.js:98:23)
    at makeArrowTable (/tmp/.mount_Reor_0UZnYj8/resources/app.asar/node_modules/vectordb/dist/arrow.js:222:16)
    at LocalTable.add (/tmp/.mount_Reor_0UZnYj8/resources/app.asar/node_modules/vectordb/dist/index.js:197:46)
    at async Xi.add (/tmp/.mount_Reor_0UZnYj8/resources/app.asar/dist-electron/main/index.js:213:2568)
    at async Bi (/tmp/.mount_Reor_0UZnYj8/resources/app.asar/dist-electron/main/index.js:213:404)
    at async IpcMainImpl.<anonymous> (/tmp/.mount_Reor_0UZnYj8/resources/app.asar/dist-electron/main/index.js:216:6266)
done adding

Anything wrong on my side?

**Comment by samlhuillier** [comment]
Which node version are you using?

I just downgraded to node 18 for testing and experienced this. Could you try upgrading to latest version? node 20.11.1

Did you experience this somehow in the released binary or just when you ran from source?

**Comment by samlhuillier** [comment]
Update: I think this is related to the lancedb update. Looking into debugging the issue now

**Comment by arnwas** [comment]
I used the app image version mentioned in the beginning of my comment. Should I try node 20 or wait for your other investigations?

**Comment by samlhuillier** [comment]
Ah gotcha. I think I've managed to fix it, related indeed to lancedb update. Will let you know when new release is out.

**Comment by samlhuillier** [comment]
Fix is out: https://github.com/reorproject/reor/releases/tag/v0.1.46
Could you download it and confirm that it works?
